# Ympäristömuuttujat write-apille
GCP_PROJECT: "uutisseuranta-activitystreams"
BQ_DATASET: "activitystreams"
BQ_SOCIAL_DATASET: "activitystreams_social"
BQ_LOCATION: "europe-north1"
SERVICE_ACCOUNT_EMAIL: "backend@uutisseuranta-activitystreams.iam.gserviceaccount.com"
GOOGLE_CLIENT_ID: "754758809337-fakeclientid.apps.googleusercontent.com"
CLOUD_RUN_SERVICE_URL: "https://write-api-7y62heo36a-lz.a.run.app"
ALLOW_MOCK_AUTH: "false"
